site_name: HANA XSC 基础培训


repo_name: ZhiminJenkins/docs
repo_url: https://github.wdf.sap.corp/ZhiminJenkins/docs
copyright: 'Copyright &copy; 2020 - SAP Cloud Platform'
theme: material
markdown_extensions:
- admonition
- codehilite
- pymdownx.superfences

pages:
- 建立开发环境: 'index.md'
- XS项目文件及激活: 'xs-project.md'
- HDBDD文件: 'db-getting-started.md'
- 数据导入: 'data-load.md'
- XSODATA: 'xsodata.md'
- 创建视图: 'view.md'
- XSJS: 'xsjs.md'
- 图形化建模 Calculation View: 'modeling.md'
- ODATA for Calculation View: 'calculationview-odata.md'
- 脚本建模 Calculation View: 'scripted-modeling.md'
