site_name: HANA XSC Docs


repo_name: ZhiminJenkins/docs
repo_url: https://github.wdf.sap.corp/ZhiminJenkins/docs
copyright: 'Copyright &copy; 2020 - SAP Cloud Platform'
theme: material
markdown_extensions:
- admonition
- codehilite
- pymdownx.superfences

pages:
- Introduction: 'index.md'
- Getting Started: 'getting-started.md'
