site_name: HANA XSC 基础培训


repo_name: ZhiminJenkins/docs
repo_url: https://github.wdf.sap.corp/ZhiminJenkins/docs
copyright: 'Copyright &copy; 2020 - SAP Cloud Platform'
theme: material
markdown_extensions:
- admonition
- codehilite
- pymdownx.superfences

pages:
- 开发环境介绍: 'index.md'
- 使用hdbdd文件建立数据库表结构: 'hdbdd-getting-started.md'
