site_name: HANA XSC 基础培训


repo_name: ZhiminJenkins/docs
repo_url: https://github.wdf.sap.corp/ZhiminJenkins/docs
copyright: 'Copyright &copy; 2020 - SAP Cloud Platform'
theme: material
markdown_extensions:
- admonition
- codehilite
- pymdownx.superfences

pages:
- 建立开发环境: 'index.md'
- XS项目文件及激活: 'db-getting-started.md'
